HW3
thegoldenbeetle/RecoServiceTemplate pull request #3
Opened 2022-12-06 23:42 UTC by thegoldenbeetle

Были сделанный как онлайн, так и офлайн реализации модели. Но ни на одном устройстве не прошло. Везде бот выдаёт:
```
Request timeout, please, check if service responds fast enough
```

2022-12-09 23:02 UTC, groundmax requested changes
Ребят, сейчас могу поставить максимум 18 баллов за дз. Может я, конечно, просмотрел, но я не увидел: блендинга моделей (4 балла) и другие варианты ранжирования (2 балла). Поправьте меня, если я ошибаюсь. Если еще это сделаете, то будет итого 24 балла, т.к. у вас оффлайн рекомендации.

Хак с `filter_viewed=False` для пункта `сделать кол-во рекомендаций не меньше N (2 балла)` хоть и очень-очень плохой, но технически задание выполнено, поэтому засчитываю)

2022-12-10 16:58 UTC, thegoldenbeetle commented on service/api/models/offline_model.py
> +        if user_id < len(self._data) and self._data[user_id] is not None:
Тут просто сделано немного странно: `self.data` это `list`.

2022-12-11 15:04 UTC, groundmax reviewed
Напоминаю, пожалуйста, если исправили или не исправили мои комментарии пишите в них "Done/Fixed" итд

Вопрос, почему у вас так сильно расходятся метрики по оффлайн и онлайн модели?
Приложите, пожалуйста, скрин ответов вашего сервиса из браузера для пользователей: 425823, 964868, 327683, 524297

После этого выставлю оценки в таблицу

2022-12-11 15:48 UTC, groundmax approved these changes

2023-01-09 02:19 UTC, merged